### ISSUE TITLE
Updated Home Assistant config

### ISSUE THREAD

**Issue by AlbertHakvoort** [NMichas/cubesensors#2]
```
sensor:
  - platform: rest 
    name: cubesensor_unit1
    resource: http://XXXXXXX/data/XXXXXXX
    json_attributes:
      - humidity
      - light
      - noisedba
      - pressure
      - temp
      - voc
      - voc_resistance
      - battery
      - charging
    value_template: 'OK'
    scan_interval: 15 
 
  - platform: template
    sensors:
      cubesensor_unit1_battery:
        friendly_name: unit1 battery 
        value_template: '{{ states.sensor.cubesensor_unit1.attributes["battery"] }}'        
  - platform: template
    sensors:
      cubesensor_unit1_charging:
        friendly_name: unit1 charging 
        value_template: '{{ states.sensor.cubesensor_unit1.attributes["charging"] }}'        
  - platform: template
    sensors:
      cubesensor_unit1_humidity:
        friendly_name: unit1 Humidity
        value_template: '{{ states.sensor.cubesensor_unit1.attributes["humidity"] }}'
        device_class: humidity
        unit_of_measurement: '%'
  - platform: template
    sensors:
      cubesensor_unit1_light:
        friendly_name: unit1 Light
        value_template: '{{ states.sensor.cubesensor_unit1.attributes["light"] }}'
        device_class: illuminance
        unit_of_measurement: 'lx'
  - platform: template
    sensors:
      cubesensor_unit1_noise:
        friendly_name: unit1 Noise
        value_template: '{{ states.sensor.cubesensor_unit1.attributes["noisedba"] }}'        
        unit_of_measurement: 'dbA'
  - platform: template
    sensors:
      cubesensor_unit1_pressure:
        friendly_name: unit1 Pressure
        value_template: '{{ states.sensor.cubesensor_unit1.attributes["pressure"] }}'
        device_class: pressure
        unit_of_measurement: 'mbar'
  - platform: template
    sensors:  
      cubesensor_unit1_temperature:
        friendly_name: unit1 Temperature
        value_template: '{{ states.sensor.cubesensor_unit1.attributes["temp"] }}'
        device_class: temperature
        unit_of_measurement: '°C'
```
